### ISSUE TITLE
Review part 3

### ISSUE THREAD

**Issue by matteodelucchi** [t4d-gmbh/ci-cd-workflows#10]

**Comment by j-i-l** [comment]
@matteodelucchi the content is reworked up to (excluding) the runners part. Maybe you could already have a look at the first half.

**Comment by j-i-l** [comment]
> [@matteodelucchi](https://github.com/matteodelucchi) the content is reworked up to (excluding) the runners part. Maybe you could already have a look at the first half.

Actually, I'll rework the github and gitlab parts somewhat. I'm not happy with them.

**Comment by j-i-l** [comment]
ok, we have a first version of part 3 :)
